-- Задание 1(st_62): [Создать представление по выручке менеджеров]
DROP VIEW IF EXISTS DW.SALES_BY_REGION;

CREATE VIEW DW.SALES_BY_REGION AS
WITH
	ORD_REGION AS (
		SELECT DISTINCT
			ORDER_ID,
			REGION
		FROM
			PUBLIC.ORDERS
	)
SELECT
	P.PERSON AS MANAGER,
	R.REGION,
	SUM(F.SALES) AS SALES,
	SUM(F.PROFIT) AS PROFIT,
	COUNT(DISTINCT F.ORDER_ID) AS ORDERS_CNT,
	CASE
		WHEN SUM(F.SALES) = 0 THEN 0
		ELSE SUM(F.PROFIT) / SUM(F.SALES)
	END AS PROFIT_MARGIN
FROM
	DW.SALES_FACT F
	JOIN ORD_REGION R ON R.ORDER_ID = F.ORDER_ID
	JOIN PUBLIC.PEOPLE P ON P.REGION = R.REGION
GROUP BY
	P.PERSON,
	R.REGION;

-- Задание 2(st_62): [Определить среднюю прибыль по категориям]
DROP VIEW IF EXISTS DW.AVG_PROFIT_BY_CATEGORY;

CREATE VIEW DW.AVG_PROFIT_BY_CATEGORY AS
WITH
	PER_ORDER AS ( -- считаем прибыль на уровне заказа внутри категории
		SELECT
			P.CATEGORY,
			F.ORDER_ID,
			SUM(F.PROFIT) AS PROFIT_PER_ORDER
		FROM
			DW.SALES_FACT F
			JOIN DW.PRODUCT_DIM P ON P.PROD_ID = F.PROD_ID
		GROUP BY
			P.CATEGORY,
			F.ORDER_ID
	)
SELECT
	CATEGORY,
	ROUND(AVG(PROFIT_PER_ORDER)::NUMERIC, 2) AS AVG_PROFIT_PER_ORDER, -- средняя прибыль на заказ
	ROUND(SUM(PROFIT_PER_ORDER)::NUMERIC, 2) AS TOTAL_PROFIT, -- суммарная прибыль категории
	COUNT(DISTINCT ORDER_ID) AS ORDERS_CNT -- число заказов в категории
FROM
	PER_ORDER
GROUP BY
	CATEGORY
ORDER BY
	AVG_PROFIT_PER_ORDER;

-- Задание 3(st_62): [Найти количество заказов по способам доставки]
DROP VIEW IF EXISTS DW.ORDERS_BY_SHIPMODE;

CREATE VIEW DW.ORDERS_BY_SHIPMODE AS
SELECT
	S.SHIPPING_MODE,
	COUNT(DISTINCT F.ORDER_ID) AS ORDERS_CNT
FROM
	DW.SALES_FACT F
	JOIN DW.SHIPPING_DIM S ON S.SHIP_ID = F.SHIP_ID
GROUP BY
	S.SHIPPING_MODE;